# This is a comment - this workflow will sync changes from ellipse-science/sondr to clessnverse/sondr
name: Sync Fork

# Controls when the workflow will run
on:
  # Runs every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Uncomment these lines if you want it to run on every push to main branch
  push:
    branches: [ main ]

jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    steps:
      # Step 1: Check out your repository - Updated to v4
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: clessnverse/sondr
          token: ${{ secrets.SYNC_PAT }}
          fetch-depth: 0
      
      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      
      # Step 3: Add the original repository as a remote
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ellipse-science/sondr.git
      
      # Step 4: Fetch all branches from both remotes
      - name: Fetch upstream changes
        run: |
          git fetch upstream
          git fetch origin
      
      # Step 5: Merge changes from upstream
      - name: Sync fork
        run: |
          # Make sure we're on the main branch
          git checkout main
          
          # Merge changes from upstream/main
          git merge upstream/main --allow-unrelated-histories
          
          # Push changes to origin (your fork)
          git push origin main

      # Step 6: Report status
      - name: Report Status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "Sync completed successfully!"
          else
            echo "Sync failed. Check the logs above for details."
          fi
